### ISSUE TITLE
Associate clue with journal entry

### ISSUE THREAD

**Issue by kelseyc18** [philipclaude/geografun#13]
Should not be able to add more than one entry for any given clue

**Comment by philipclaude** [comment]
why? if we offer the ability to delete guide entries, then why do we want this?

**Comment by kelseyc18** [comment]
When someone modifies his/her answer to a question for a given clue, it should replace the old entry with the updated entry. Otherwise, you can have multiple entries for the same clue, defeating the purpose of only allowing guesses once you have at least X pieces of evidence.

**Comment by philipclaude** [comment]
ah okay got it
